name    'alup-rbenv'
version '1.0.0'
author 'alup'
license 'MIT'
summary 'rbenv Ruby Version Manager module'
description 'Puppet module for rbenv Ruby Version Manager'
project_page 'https://github.com/alup/puppet-rbenv'
